services:
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    networks:
      - salesnet
    ports:
      - "27018:27018"

volumes:
  mongodata:

networks:
  salesnet:
    driver: bridge